version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
workflows:
    build-and-test:
      jobs:
        - build-and-test
        