version: 2.1
jobs:
  build-and-test:
  executor:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - store_test_results:
                path: ./reports/junit/
            - store_artifacts:
                path: ./reports/junit
workflows:
    build-and-test:
      jobs:
        - build-and-test
        